name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  package_dpkg:
    name: Package for Debian/Ubuntu
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Fix Checkout
        run: |
          git fetch --force --tags

      - name: Print env vars
        run: printenv

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      # from here to 'start services' is a docker test suite to make 'make test' work
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose

      # need to do this before we start the services as they need the TLS creds
      - name: Create test certs for TLS
        run: |
          make test-certs
          chmod 777 ./contrib/tls/*

      - name: Start services
        run: docker-compose up -d
        working-directory: ./

      - name: Prep deps
        run: make build-dep

      # 'make build' is an upstream target not suitable for us
      - name: Build binary
        run: make redis_exporter

      - name: Build dpkg
        run: make dpkg

      - name: Upload dpkg
        uses: actions/upload-artifact@v4
        with:
          name: packages-dpkg
          path: "*.deb"

  upload_release:
    name: Upload Release Assets
    needs:
      - package_dpkg
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Fix Checkout
        run: |
          git fetch --force --tags

      - name: Get Tag Type
        id: get_tagtype
        run: |
          TYPE=$(git cat-file -t $GITHUB_REF || echo UNKNOWN)
          echo "TAGTYPE=$TYPE" >> $GITHUB_OUTPUT
          echo ==========
          echo REF=$GITHUB_REF
          echo TAGTYPE=$TYPE

      - name: Fetch all Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Upload Assets to Release
        if: steps.get_tagtype.outputs.TAGTYPE == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            artifacts/packages-dpkg/*.deb

      - name: Upload Assets to Nexus
        if: github.ref == 'refs/heads/main'
        run: |
          make deploy NEXUS_CREDS="${{ vars.NEXUS1_RW_USERNAME }}:${{ secrets.NEXUS1_RW_PASSWORD }}"

