name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  package_dpkg:
    name: Package for Debian/Ubuntu
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Fix Checkout
        run: |
          git fetch --force --tags

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Build binaries
        run: make build

      - name: Build
        run: make dpkg

      - name: Upload dpkg
        uses: actions/upload-artifact@v4
        with:
          name: packages-dpkg
          path: "*.deb"
